---
# Infra (auth0)
- import_playbook: auth0/login.yml
  vars:
    app_environment: "{{ APP_ENVIRONMENT }}"
    auth0_domain: "{{ AUTH0_DOMAIN }}"
    auth0_client_id: "{{ AUTH0_CLIENT_ID }}"
    auth0_client_secret: "{{ AUTH0_CLIENT_SECRET }}"
- import_playbook: auth0/deploy_api.yml
  vars:
    app_environment: "{{ APP_ENVIRONMENT }}"

# Infra (database mongodb)
- import_playbook: mongodb/create.yml
  vars:
    app_environment: "{{ APP_ENVIRONMENT }}"
    google_region: "{{ GOOGLE_REGION }}"
    project_id: "{{ MONGODB_ATLAS_PROJECT_ID }}"
    public_api_key: "{{ MONGODB_ATLAS_PUBLIC_KEY }}"
    private_api_key: "{{ MONGODB_ATLAS_PRIVATE_KEY }}"

# Infra (gcloud)
- import_playbook: gcloud/deploy.yml
  vars:
    app_environment: "{{ APP_ENVIRONMENT }}"

# Backend functions
- import_playbook: ../../App.Function.Integration.Ynab/deploy/deploy.yml
  vars:
    app_environment: "{{ APP_ENVIRONMENT }}"
    app_image_tag: "{{ APP_TAG }}"
    app_frontend: "{{ APP_FRONTEND }}"
    google_region: "{{ GOOGLE_REGION }}"
    google_project_id: "{{ GOOGLE_PROJECT_ID }}"
    sentry_dsn: "{{ SENTRY_DSN }}"
    database_connection_string: "{{ mongodb_connection_string_admin }}"
    auth0_domain: "{{ AUTH0_DOMAIN }}"
    ynab_client_id: "{{ YNAB_CLIENT_ID }}"
    ynab_client_secret: "{{ YNAB_CLIENT_SECRET }}"

# Frontend
- import_playbook: ../../frontend-web/deploy/deploy.yml
  vars:
    app_environment: "{{ APP_ENVIRONMENT }}"
    app_project_name: "{{ GOOGLE_PROJECT_ID }}"
    cloudflare_api_token: "{{ CLOUDFLARE_API_TOKEN }}"
    cloudflare_account_id: "{{ CLOUDFLARE_ACCOUNT_ID }}"
    auth0_domain: "{{ AUTH0_DOMAIN }}"
    service_urls:
      function_integration_ynab_url: "{{ function_integration_ynab_url }}"
