---
- name: Set variables
  set_fact:
    password: "{{ lookup('community.general.random_string', length=12, special=false) }}"

- name: Get atlas user info {{ username }}
  shell: atlas dbusers describe "{{ username }}" --projectId="{{ project_id }}" -o json
  register: user_info
  changed_when: false
  failed_when: false

# Create new
- name: Create atlas user "{{ username }}"
  when: user_info.rc != 0
  shell: atlas dbusers create \
    --projectId="{{ project_id }}" \
    --scope="CLUSTER,{{ app_environment }}" \
    --username="{{ username }}" \
    --password="{{ password }}" \
    --role="{{ role }}"

# Update / roll password
- name: Update atlas user "{{ username }}"
  when: user_info.rc == 0
  shell: atlas dbusers update "{{ username }}" \
    --projectId="{{ project_id }}" \
    --password="{{ password }}"

- name: Find connection string
  register: connection_string_info
  shell: atlas serverless describe "{{ app_environment }}" \
    --projectId="{{ project_id }}" \
    -o json | jq -r ".connectionStrings.standardSrv"

- name: Set connection string variable
  set_fact: >-
    mongodb_connection_string_{{ username }}={{ connection_string_info.stdout |
    replace('mongodb+srv://', 'mongodb+srv://' + username + ':' + password + '@') }}
