---
- import_playbook: deploy_auth0_client.yml
  vars:
      frontend_web_url: "{{ 'https://' + app_environment + '.' + app_project_name + '.pages.dev/' | regex_replace('^https://main.', 'https://') }}"
- import_playbook: deploy_cf_pages.yml
