apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: import.${DEPLOY_ENV}
spec:
  template:
    spec:
      containerConcurrency: 1
      containers:
        - image: ${IMAGE}
          resources:
            limits:
              cpu: "1"
              memory: 512Mi