apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ${DEPLOY_ENV}.import
spec:
  template:
    spec:
      containerConcurrency: 1
      containers:
        - image: ${IMAGE_TAG}
          resources:
            limits:
              cpu: "1"
              memory: 512Mi