apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ${SERVICE}
  labels:
    environment: ${DEPLOY_ENV}
spec:
  template:
    spec:
      containerConcurrency: 1
      containers:
        - image: ${IMAGE}
          env:
            - name: DOTNET_ENVIRONMENT
              value: ${DEPLOY_ENV}
            - name: Database__ConnectionString
              value: ${Database__ConnectionString}
            - name: Database__DatabaseName
              value: ${Database__DatabaseName}
            - name: Sentry__Dsn
              value: ${Sentry__Dsn} 
          resources:
            limits:
              cpu: "1"
              memory: 512Mi