name: 'Configure Docker tools'
description: 'Setup Docker tools and authentication'
inputs:
    google_workload_identity_provider:
        required: true
        description: "Google workload identity provider, created in `deploy/setup.sh`."
    google_service_account:
        required: true
        description: "Google service account email, created in `deploy/setup.sh`."
    container_registry:
        required: true
        description: "Container registry to login to"
runs:
    using: "composite"
    steps:
    -   uses: google-github-actions/auth@v1
        id: google_auth
        with:
            token_format: 'access_token'
            workload_identity_provider: ${{ inputs.google_workload_identity_provider }}
            service_account: ${{ inputs.google_service_account }}
            access_token_lifetime: 300s
    -   uses: docker/login-action@v2
        with:
            registry: ${{ inputs.container_registry }}
            username: oauth2accesstoken
            password: ${{ steps.google_auth.outputs.access_token }}
    -   uses: docker/setup-buildx-action@v2
