---
- name: Deploy App.Function.Integration.Ynab auth0 api
  gather_facts: false
  hosts: localhost
  vars:
    auth0_api_identifier: "public"
    auth0_scopes:
      - function.integration.ynab
  tasks:
    - include_tasks: ensure_api.yml
    - include_tasks: ensure_role.yml
      vars:
        auth0_role_name: "User"
