---
- name: Api info "{{ auth0_api_identifier }}"
  shell: auth0 apis show "{{ auth0_api_identifier }}"
  register: auth0_api_info
  changed_when: false
  failed_when: false

# Create new
- name: Create auth0 api "{{ auth0_api_identifier }}"
  when: auth0_api_info.rc != 0
  shell: auth0 apis create \
    --name="{{ auth0_api_identifier }}" \
    --identifier="{{ auth0_api_identifier }}" \
    --offline-access=false \
    --scopes="connect,disconnect,status" \
    --no-input
