---
- name: Rule info "{{ auth0_rule_name }}"
  shell: auth0 rules list --json | jq -e -s ".[0], .[] | .[] | select(.name == \"{{ app_environment }}--{{ auth0_rule_name }}\")"
  register: auth0_rule_exists
  changed_when: false
  failed_when: false

# Create new rule
- name: Create rule "{{ auth0_rule_name }}"
  when: auth0_rule_exists.rc != 0
  shell: auth0 rules create \
      --name="{{ app_environment }}--{{ auth0_rule_name }}" \
      --script="{{ auth0_rule_script }}" \
      --template=empty \
      --enabled=true
# Get rule id
- name: Rule info "{{ auth0_rule_name }}"
  register: auth0_rule_id_info
  shell: auth0 rules list --json 2>/dev/null \
      | jq -e -r ".[] | select(.name == \"{{ app_environment }}--{{ auth0_rule_name }}\") | .id"

- name: Update rule "{{ auth0_rule_name }}"
  when: auth0_rule_exists.rc == 0
  shell: auth0 rules update {{ auth0_rule_id_info.stdout }} \
      --name="{{ app_environment }}--{{ auth0_rule_name }}" \
      --script="{{ auth0_rule_script }}" \
      --force \
      --enabled=true
