name: Delete resources
on:
    workflow_call:
        inputs:
            environment:
                required: true
                type: string

        secrets:
            GOOGLE_WORKLOAD_IDENTITY_PROVIDER:
                required: true
            GOOGLE_SERVICE_ACCOUNT_EMAIL:
                required: true
            GOOGLE_PROJECT_ID:
                required: true
            GOOGLE_REGION:
                required: true
            SENTRY_DSN:
                required: true
            CLOUDFLARE_API_TOKEN:
                required: true
            CLOUDFLARE_ACCOUNT_ID:
                required: true
            MONGODB_ATLAS_PUBLIC_KEY:
                required: true
            MONGODB_ATLAS_PRIVATE_KEY:
                required: true
            MONGODB_ATLAS_PROJECT_ID:
                required: true
            AUTH0_DOMAIN:
                required: true
            AUTH0_CLIENT_ID:
                required: true
            AUTH0_CLIENT_SECRET:
                required: true

jobs:
    delete_resources:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
            deployments: write
        steps:
        -   uses: actions/checkout@v3
        -   uses: ./.github/actions/config_cli_tools
            with:
                google_workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
                google_service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
        -   run: ./App.Deploy/deploy.sh rm 
            env:
                APP_ENVIRONMENT: ${{ inputs.environment }}
                PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
                GOOGLE_REGION: ${{ secrets.GOOGLE_REGION }}
                GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
                MONGODB_ATLAS_PUBLIC_KEY: ${{ secrets.MONGODB_ATLAS_PUBLIC_KEY }}
                MONGODB_ATLAS_PRIVATE_KEY: ${{ secrets.MONGODB_ATLAS_PRIVATE_KEY }}
                MONGODB_ATLAS_PROJECT_ID: ${{ secrets.MONGODB_ATLAS_PROJECT_ID }}
                CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
                AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
                AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
