name: Delete environment
on:
    workflow_dispatch: 
        inputs: 
            environment:
                required: true
                description: "The environment to delete"
                type: environment

jobs:
    delete_containers:
        uses: ./.github/workflows/delete_containers.yaml
        secrets: inherit
        with:
            environment: ${{ inputs.environment }}

    delete_resources:
        uses: ./.github/workflows/delete_resources.yaml
        secrets: inherit
        with:
            environment: ${{ inputs.environment }}