name: Deploy environment

on:
    push:
        branches:
        - main
        - beta
        - alpha

jobs:
    deploy_slug:
        runs-on: ubuntu-latest
        steps:
        -   uses: rlespinasse/github-slug-action@v4
        -   id: environment
            run: echo "var=${{ env.GITHUB_REF_SLUG_URL }}" >> $GITHUB_OUTPUT
        -   id: tag
            run: echo "var=${{ env.GITHUB_SHA_SHORT }}" >> $GITHUB_OUTPUT
        -   id: project_url_slug
            run: echo "var=${{ secrets.GOOGLE_PROJECT_ID }}" >> $GITHUB_OUTPUT
        outputs:
            environment: ${{ steps.environment.outputs.var }}
            tag: ${{ steps.tag.outputs.var }}
            project_url_slug: ${{ steps.project_url_slug.outputs.var }}

    build:
        needs: [ deploy_slug ]
        uses: ./.github/workflows/build.yaml
        secrets: inherit
        with:
            environment: ${{ needs.deploy_slug.outputs.environment }}
            tag: ${{ needs.deploy_slug.outputs.tag }}

    deploy_prerelease:
        needs: [ deploy_slug, build ]
        if: "${{ needs.deploy_slug.outputs.environment != 'main' }}"
        uses: ./.github/workflows/deploy.yaml
        secrets: inherit
        concurrency: ${{ needs.deploy_slug.outputs.environment }}
        with:
            environment: ${{ needs.deploy_slug.outputs.environment }}
            tag: ${{ needs.deploy_slug.outputs.tag }}
            environment_url: "https://${{ needs.deploy_slug.outputs.environment }}.${{ needs.deploy_slug.outputs.project_url_slug }}.pages.dev"
    deploy_production:
        needs: [ deploy_slug, build ]
        if: "${{ needs.deploy_slug.outputs.environment == 'main' }}"
        uses: ./.github/workflows/deploy.yaml
        secrets: inherit
        concurrency: ${{ needs.deploy_slug.outputs.environment }}
        with:
            environment: ${{ needs.deploy_slug.outputs.environment }}
            tag: ${{ needs.deploy_slug.outputs.tag }}
            environment_url: "https://${{ needs.deploy_slug.outputs.project_url_slug }}.pages.dev"

    delete_containers:
        needs: [ deploy_slug, build ]
        uses: ./.github/workflows/delete_containers.yaml
        secrets: inherit
        concurrency:
            group: ${{ needs.deploy_slug.outputs.environment }}
            cancel-in-progress: true
        if: ${{ always() }}
        with:
            environment: ${{ needs.deploy_slug.outputs.environment }}
            keep: 2
            grace: "7d"
