name: Deploy
on:
    release:
        types: [published]

jobs:
    build_images:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                dotnet-version: [ '6.0.x' ]
                project: [ 'App.Function.Banktransaction.Import' ]
        steps:
        -   uses: actions/checkout@v2
        -   uses: crazy-max/ghaction-docker-meta@v4
            id: docker_meta
            with:
                images: ghcr.io/${{ github.repository }}/${{ matrix.project }}
        -   uses: docker/setup-buildx-action@v1.6.0
        -   uses: docker/login-action@v1
            with:
                registry: ghcr.io
                username: ${{ github.repository_owner }}
                password: ${{ secrets.GITHUB_TOKEN }}
        -   uses: docker/build-push-action@v2.7.0
            with:
                context: .
                push: true
                tags: ${{ steps.docker_meta.outputs.tags }}
                cache-from: type=gha
                cache-to: type=gha,mode=max
                
    deploy:
        runs-on: ubuntu-latest
        if: startsWith(github.ref, 'refs/tags/v') && endsWith(github.ref, '${{ matrix.environment }}')
        needs: 
            - build_images
        permissions:
            contents: 'read'
            id-token: 'write'
        strategy:
            matrix:
                project: [ 'App.Function.Banktransaction.Import' ]
                environment: [ 'beta' ]
        steps:
            - uses: 'actions/checkout@v3'
            - id: 'auth'
              name: 'Authenticate to Google Cloud'
              uses: 'google-github-actions/auth@v0'
              with:
                  workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
                  service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
            - id: 'deploy'
              uses: 'google-github-actions/deploy-cloudrun@v0'
              with:
                  metadata: '${{ matrix.project }}'
                  env_vars: 'DEPLOY_ENV=${{ matrix.environment }}'