name: Deploy
on:
    pull_request: 
    push:
        branches:
            - 'main'
            - 'beta'

jobs:
    build_images:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                project: [ 'App.Function.Banktransaction.Import' ]
        steps:
        -   uses: actions/checkout@v2
        -   uses: crazy-max/ghaction-docker-meta@v4
            id: docker_meta
            with:
                images: ghcr.io/${{ github.repository }}/${{ matrix.project }}
        -   uses: docker/setup-buildx-action@v2
        -   uses: docker/login-action@v2
            with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
        -   uses: docker/build-push-action@v2.7.0
            with:
                context: .
                file: '${{ matrix.project }}/Dockerfile'
                push: true
                tags: ${{ steps.docker_meta.outputs.tags }}
                cache-from: type=gha
                cache-to: type=gha,mode=max
                
    deploy:
        runs-on: ubuntu-latest
        #if: startsWith(github.ref, 'refs/tags/v') && endsWith(github.ref, '${{ matrix.environment }}')
        needs: 
            - build_images
        permissions:
            contents: 'read'
            id-token: 'write'
        strategy:
            matrix:
                project: [ 'App.Function.Banktransaction.Import' ]
                environment: [ 'beta' ]
                region: [ 'europe-central2' ]
        steps:
            - run: 'echo ${{ github.ref }}'
            - uses: 'actions/checkout@v3'
            - uses: 'google-github-actions/auth@v0'
              with:
                  workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
                  service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
            - uses: crazy-max/ghaction-docker-meta@v4
              id: docker_meta
              with:
                  images: ghcr.io/${{ github.repository }}/${{ matrix.project }}
            - uses: mshick/fast-envsubst@v1
              env:
                  DEPLOY_ENV: ${{ matrix.environment }}
                  IMAGE: ${{ steps.docker_meta.outputs.tags }}
              with:
                  in-file: ${{ matrix.project }}/service.yaml
                  out-file: ${{ matrix.project }}/service.deploy.yaml
            - run: cat ${{ matrix.project }}/service.deploy.yaml
            - uses: 'google-github-actions/deploy-cloudrun@v0'
              with:
                  metadata: '${{ matrix.project }}/service.deploy.yaml'
                  region: ${{ matrix.region }}