name: Deploy
on:
    push:
        branches:
            - 'main'
            - 'beta'

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                project: [
                    { folder: 'App.Function.Banktransaction.Import', service: 'function-banktransaction-import' }
                ]
        permissions:
            contents: 'read'
            id-token: 'write'
        steps:
        - uses: actions/checkout@v3
        - uses: google-github-actions/auth@v0
          id: google_auth
          with:
              token_format: 'access_token'
              workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
              service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
        - uses: docker/login-action@v2
          with:
              registry: gcr.io
              username: oauth2accesstoken
              password: ${{ steps.google_auth.outputs.access_token }}
        - uses: crazy-max/ghaction-docker-meta@v4
          id: docker_meta
          with:
              images: gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}/${{ matrix.project.folder }}
        - uses: docker/setup-buildx-action@v2
        - uses: docker/build-push-action@v2.7.0
          with:
              context: .
              file: '${{ matrix.project.folder }}/Dockerfile'
              push: true
              tags: ${{ steps.docker_meta.outputs.tags }}
              cache-from: type=gha
              cache-to: type=gha,mode=max
    
    deploy:
        runs-on: ubuntu-latest
        needs: 
            - build
        permissions:
            contents: 'read'
            id-token: 'write'
        strategy:
            matrix:
                project: [
                    { folder: 'App.Function.Banktransaction.Import', service: 'function-banktransaction-import' }
                ]
                region: [ 'europe-central2' ]
        steps:
            - uses: actions/checkout@v3
            - uses: crazy-max/ghaction-docker-meta@v4
              id: docker_meta
              with:
                  images: gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}/${{ matrix.project.folder }}
            - uses: actions/github-script@v6
              id: environment
              with:
                  script: |
                    return context.ref
                      .replace(/^refs\//, '')
                      .replace(/\/merge$/, '')
                      .replace(/\//, '-')
                  result-encoding: string
            - uses: mshick/fast-envsubst@v1
              env:
                  SERVICE: ${{ matrix.project.service }}
                  DEPLOY_ENV: ${{steps.environment.outputs.result}}
                  IMAGE: ${{ steps.docker_meta.outputs.tags }}
                  Database__ConnectionString: ${{ secrets.DATABASE__CONNECTIONSTRING }}
                  Database__DatabaseName: ${{steps.environment.outputs.result}}
              with:
                  in-file: ${{ matrix.project.folder }}/service.yaml
                  out-file: ${{ matrix.project.folder }}/service.deploy.yaml
            - run: cat ${{ matrix.project.folder }}/service.deploy.yaml
            - uses: google-github-actions/auth@v0
              id: google_auth
              with:
                workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
                service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
            - uses: google-github-actions/deploy-cloudrun@v0
              with:
                  metadata: ${{ matrix.project.folder }}/service.deploy.yaml
                  region: ${{ matrix.region }}
