name: Deploy
on:
    pull_request: 
    push:
        branches:
            - 'main'
            - 'beta'

jobs:
    build_images:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                project: [
                    { folder: 'App.Function.Banktransaction.Import', service: 'function-banktransaction-import' }
                ]
        steps:
        -   uses: actions/checkout@v2
        -   uses: crazy-max/ghaction-docker-meta@v4
            id: docker_meta
            with:
                images: ghcr.io/${{ github.repository }}/${{ matrix.project.folder }}
        -   uses: docker/setup-buildx-action@v2
        -   uses: docker/login-action@v2
            with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
        -   uses: docker/build-push-action@v2.7.0
            with:
                context: .
                file: '${{ matrix.project.folder }}/Dockerfile'
                push: true
                tags: ${{ steps.docker_meta.outputs.tags }}
                cache-from: type=gha
                cache-to: type=gha,mode=max
                
    deploy:
        runs-on: ubuntu-latest
        needs: 
            - build_images
        permissions:
            contents: 'read'
            id-token: 'write'
        strategy:
            matrix:
                project: [
                    { folder: 'App.Function.Banktransaction.Import', service: 'function-banktransaction-import' }
                ]
                region: [ 'europe-central2' ]
        steps:
            - run: 'echo ${{ github.ref }}'
            - uses: 'actions/checkout@v3'
            - uses: 'google-github-actions/auth@v0'
              with:
                  workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
                  service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
            - uses: crazy-max/ghaction-docker-meta@v4
              id: docker_meta
              with:
                  images: ghcr.io/${{ github.repository }}/${{ matrix.project.folder }}
            - uses: actions/github-script@v6
              id: environment
              with:
                  script: |
                    return context.ref
                      .replace(/^refs\//, '')
                      .replace(/\/merge$/, '')
                      .replace(/\//, '-')
                  result-encoding: string
            - uses: mshick/fast-envsubst@v1
              env:
                  SERVICE: ${{ matrix.project.service }}
                  DEPLOY_ENV: ${{steps.environment.outputs.result}}
                  IMAGE: ${{ steps.docker_meta.outputs.tags }}
              with:
                  in-file: ${{ matrix.project.folder }}/service.yaml
                  out-file: ${{ matrix.project.folder }}/service.deploy.yaml
            - run: cat ${{ matrix.project.folder }}/service.deploy.yaml
            - uses: 'google-github-actions/deploy-cloudrun@v0'
              with:
                  metadata: '${{ matrix.project.folder }}/service.deploy.yaml'
                  region: ${{ matrix.region }}
