name: Release

on:
    push:
        branches:
        - main
        - master
        - alpha
        - beta

jobs:
    release:
        runs-on: ubuntu-20.04
        steps:
        -   uses: actions/checkout@v3
            with:
                persist-credentials: false
        -   uses: cycjimmy/semantic-release-action@v3
            with:
                semantic_version: 20
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
