name: Integration tests
on:
    pull_request:

jobs:
    deploy_slug:
        runs-on: ubuntu-latest
        steps:
        -   uses: rlespinasse/github-slug-action@v4
        -   id: environment
            run: echo "var=pr-${{ env.GITHUB_REF_SLUG_URL }}" >> $GITHUB_OUTPUT
        -   id: tag
            run: echo "var=${{ env.GITHUB_SHA_SHORT }}" >> $GITHUB_OUTPUT
        outputs:
            environment: ${{ steps.environment.outputs.var }}
            tag: ${{ steps.tag.outputs.var }}

    build:
        needs: [deploy_slug]
        uses: ./.github/workflows/build.yaml
        secrets: inherit
        concurrency:
            group: ${{ needs.deploy_slug.outputs.environment }}-build
            cancel-in-progress: true
        with:
            environment: ${{ needs.deploy_slug.outputs.environment }}
            tag: ${{ needs.deploy_slug.outputs.tag }}
    
    deploy:
        needs: [deploy_slug, build]
        uses: ./.github/workflows/deploy.yaml
        secrets: inherit
        concurrency: 
            group: ${{ needs.deploy_slug.outputs.environment }}-deploy
            cancel-in-progress: true
        with:
            environment: ${{ needs.deploy_slug.outputs.environment }}
            tag: ${{ needs.deploy_slug.outputs.tag }}
        
    test:
        runs-on: ubuntu-latest
        needs: [deploy_slug, deploy]
        concurrency:
            group: ${{ needs.deploy_slug.outputs.environment }}-test
            cancel-in-progress: true
        steps:
        -   run: echo "::warning file=.github/workflows/test_integration.yaml,::No integration tests implemented"
            
    delete_containers:
        needs: [build, deploy_slug, deploy, test]
        uses: ./.github/workflows/delete_containers.yaml
        secrets: inherit
        if: ${{ needs.build.result != 'skipped' && needs.deploy.result != 'skipped' && needs.test.result != 'skipped' }}
        with:
            environment: ${{ needs.deploy_slug.outputs.environment }}
            
    delete_resources:
        needs: [build, deploy_slug, deploy, test]
        uses: ./.github/workflows/delete_resources.yaml
        secrets: inherit
        if: ${{ needs.build.result != 'skipped' && needs.deploy.result != 'skipped' && needs.test.result != 'skipped' }}
        with:
            environment: ${{ needs.deploy_slug.outputs.environment }}

    test_integration_success:
        runs-on: ubuntu-latest
        needs:
        - deploy
        - test
        - delete_containers
        - delete_resources
        if: ${{ always() }}
        steps:
        -   run: "[[ '${{ needs.deploy.result }}' == 'success' && '${{ needs.test.result }}' == 'success' ]]"
