name: Test
on:
    pull_request:

jobs:
    #########################################################
    # Code quality and unit tests
    #########################################################
    test_quality:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: xt0rted/dotnet-tool-restore@v1
        - run: dotnet format --verify-no-changes --verbosity diagnostic
              
    #test_unit:
    #    runs-on: ubuntu-latest
    #    steps:
    #        - uses: actions/checkout@v2
    #        - name: use this action, test solution dir
    #          uses: zyborg/dotnet-tests-report@v1
    #          with:
    #              project_path: tests/My.Project.Tests
    #              github_token: ${{ secrets.GITHUB_TOKEN }}