name: Code quality
on:
    pull_request:

jobs:
    #########################################################
    # Code quality tests
    #########################################################
    test_quality_dotnet:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v3
        -   uses: actions/setup-dotnet@v3
            with:
                dotnet-version: 7.0
        -   run: dotnet format --verify-no-changes

    test_quality_frontend_web_typescript:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v3
        -   uses: actions/setup-node@v3
            with:
                node-version-file: frontend-web/package.json
        -   run: npm ci
            working-directory: frontend-web
        -   run: npx eslint . --ext .js,.jsx,.ts,.tsx
            working-directory: frontend-web

    test_quality_success:
        runs-on: ubuntu-latest
        needs:
        - test_quality_dotnet
        - test_quality_frontend_web_typescript
        if: ${{ always() }}
        steps:
        -   run: "[[ '${{ needs.test_quality_dotnet.result }}' == 'success' && '${{ needs.test_quality_ansible.result }}' == 'success' && '${{ needs.test_quality_frontend_web_typescript.result }}' == 'success' ]]"